global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'products-service'
    metrics_path: '/actuator/products/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          aplication: 'products-service'
  - job_name: 'orders-service'
    metrics_path: '/actuator/orders/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          aplication: 'order-service'
  - job_name: 'inventory-service'
    metrics_path: '/actuator/inventory/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          aplication: 'inventory-service'